### ISSUE TITLE
netkvm.sys causes DRIVER_POWER_STATE_FAILURE (0x9F) BSOD on repeated hibernation cycles (Windows 10 22H2 guest)

### ISSUE THREAD

**Issue by xuehuihui** [virtio-win/kvm-guest-drivers-windows#1394]
**Describe the bug**
We're encountering a BSOD issue (DRIVER_POWER_STATE_FAILURE, bugcheck 0x9F) in a Windows 10 22H2 guest using the netkvm driver. The crash occurs intermittently when performing repeated guest-initiated hibernation and power-on cycles.

**Host:**
 - Kernel version： 5.10.0
 - QEMU version： 6.0.1
 - QEMU command line 
 -netdev tap,fd=45,vhost=on,vhostfd=46,id=hostua-0597b899-65b7-418f-8361-e4cf26cc2bd7 \
 -device virtio-net-pci,netdev=hostua-0597b899-65b7-418f-8361-e4cf26cc2bd7,id=ua-0597b899-65b7-418f-8361-e4cf26cc2bd7,mac=52:54:00:10:15:81,bus=pci.4,addr=0x0,speed=1000 \
 - libvirt version：8.10.0

**VM:**
Guest OS: Windows 10 22H2 (Build 19045.x)
Hypervisor: QEMU/KVM
Virtio driver versions tested:
virtio-win-0.1.271
virtio-win-0.1.171
Affected driver: netkvm.sys (virtio network driver)

**Steps to Reproduce:**
1. Boot Windows 10 22H2 guest with netkvm driver installed.
2. From within the guest, use the "Hibernate" option in the Start menu.
3. Power the VM back on.
4. Repeat the hibernate → power on cycle several times.
5. Eventually observe a 0x9F BSOD.

**Issue Summary:**

When the Windows guest is configured to hibernate (i.e., using the “Hibernate” option in the Power menu), and the user performs multiple hibernate→power-on cycles, the VM may eventually hit a BSOD with the following signature:
`DRIVER_POWER_STATE_FAILURE (9f)
A driver has failed to complete a power IRP within a specific time.`

**Windbg Analysis (Key Points):**
IRP stack shows the netkvm driver is involved in a blocked power IRP (IRP_MJ_POWER, IRP_MN_SET_POWER)
ndis.sys is waiting in ndisWaitForKernelObject, likely on netkvm.sys completion
Bugcheck points to a power transition hang within the network driver stack

**Stack Trace (Trimmed):**

- ndis!ndisWaitForKernelObject+0x21
- ndis!ndisQuerySetMiniportEx
- ndis!ndisSetDevicePower
- ndis!ndisPowerDispatch
- nt!PopIrpWorker

**IRP Debug Output:**
`>[IRP_MJ_POWER(16), IRP_MN_SET_POWER(2)]
    \Driver\netkvm  nt!PopRequestCompletion
`

**Comment by xuehuihui** [comment]
Full MEMORY.DMP (~514MB) can be downloaded here
https://drive.google.com/file/d/1ubz-f0r0IEcMPt-CGzfT9wqEl__t1aqX/view?usp=sharing

**Comment by ybendito** [comment]
Indeed, there is one packet that indicated up and not returned.
We need to fix the hibernation flow for RX.

As as workaround you can disable hibernation in the hypervisor, for QEMU this is:
-global PIIX4_PM.disable_s4=1 (for pc) or 
-global ICH9-LPC.disable_s4=1 (for q35) 

[windbg.TXT](https://github.com/user-attachments/files/21368218/windbg.TXT)

**Comment by ybendito** [comment]
Created https://issues.redhat.com/browse/RHEL-104870

**Comment by xuehuihui** [comment]
> Indeed, there is one packet that indicated up and not returned. We need to fix the hibernation flow for RX.
> 
> As as workaround you can disable hibernation in the hypervisor, for QEMU this is: -global PIIX4_PM.disable_s4=1 (for pc) or -global ICH9-LPC.disable_s4=1 (for q35)
> 
> [windbg.TXT](https://github.com/user-attachments/files/21368218/windbg.TXT)


@ybendito Thank you very much for your reply and suggestions!
I have reviewed the code and noticed that in the hibernation flow, the following line is used to wait for all outstanding RX packets to be returned:

```
  virtual void Stop(NDIS_STATUS Reason = NDIS_STATUS_PAUSED)
  {
      if (m_State != FlowState::Running)
      {
          return;
      }
      m_State = FlowState::Stopping;
      m_StopReason = Reason;
      m_NoOutstandingItems.Clear();
      m_Counter.SetMask(StoppedMask);
      UnregisterOutstandingItem();
      m_NoOutstandingItems.Wait();
  }
```

I am considering adding a timeout mechanism here, for example:
```
m_NoOutstandingItems.Wait(timeout);
```
Do you think this approach would be appropriate?
Or do you already have a solution or plan to address this issue?
If you could share any advice or suggestions on how to handle the situation where an indicated NBL is still pending and not returned, I would greatly appreciate it.
Additionally, I am able to reliably reproduce this issue in my test environment, which should help with debugging and verifying any potential fixes.
Thank you again for your help!

**Comment by dskr999** [comment]
I believe it is a duplicate of https://github.com/virtio-win/kvm-guest-drivers-windows/issues/1221

**Comment by YanVugenfirer** [comment]
@dskr999 Was the issue solved with a new driver?

**Comment by dskr999** [comment]
@xuehuihui was the issue fixed with changes from #1221 ?..

**Comment by ybendito** [comment]
@xuehuihui @dskr999 https://github.com/virtio-win/kvm-guest-drivers-windows/issues/1221 is indeed the same. There was no response but IMO the "fix" was not correct.
Timeout approach here is not enough, as one or more packets are still held by some module in the network stack and will be returned after S4->S0 transition, this flow currently is not supported. This isssue is in the plan but there is no ETA yet.

**Comment by dskr999** [comment]
I agree.. I have no idea so far how to correctly fix this issue.

**Comment by xuehuihui** [comment]
@ybendito I captured driver logs and noticed that right before ParaNdis_PowerOff was called, there was one NetBufferList (NBL) that was indicated up at 17:50:11:127 but was never returned. For details, see the log I uploaded as error.txt.

```
01671159	netkvm.sys	4	9412	0	0	07\29\2025-17:50:11:127	 ParaNdis_RXTXDPCWorkBody
01671160	netkvm.sys	4	9412	0	0	07\29\2025-17:50:11:127	 QualifyIpPacketip_version 4, ipHeaderSize 20, protocol 1, iplen 84, L2 payload length 84
01671161	netkvm.sys	4	9412	0	0	07\29\2025-17:50:11:127	 PrintOutParsingResult[ParaNdis_CheckRxChecksum] IP packet IPCS not tested<NULL>, checksum -<NULL>
01671162	netkvm.sys	4	9412	0	0	07\29\2025-17:50:11:127	 ParaNdis_PrepareReceivedPacketdatalen 98, GSO type/flags 0:0, mss 0, 1 segments, CS 0->0
01671163	netkvm.sys	4	1532	1	0	07\29\2025-17:50:11:127	 ParaNdis6_OidRequest[ParaNdis6_OidRequest] OID type 1, id 0xFD010101(OID_PNP_SET_POWER) of 4
01671164	netkvm.sys	4	1532	1	0	07\29\2025-17:50:11:127	 ParaNdis_OnSetPower
01671165	netkvm.sys	4	260	3	0	07\29\2025-17:50:11:127	 ParaNdis_PowerOff
01671166	netkvm.sys	4	8796	0	0	07\29\2025-17:50:11:140	 ParaNdis_RXTXDPCWorkBody
```

During the ParaNdis_PowerOff handling, there were also multiple Rx DPCs in progress, but those NBLs were released directly without being indicated to the OS.

Could you help explain under what conditions an indicated packet might not be returned? I’m trying to understand what could cause this mismatch — whether it's due to upper-layer behavior or something else.

Also, your patch from issue #1221 seems to potentially address this case — I’m currently running stress tests to validate it. That said, I don’t quite understand why this patch would fix the issue。

Thanks!

[error.txt](https://github.com/user-attachments/files/21490947/error.txt)

**Comment by xuehuihui** [comment]
@ybendito @YanVugenfirer syncing the latest test, the issue still exists with the #1221 patch.

**Comment by ybendito** [comment]
Created https://issues.redhat.com/browse/RHEL-135728
